apiVersion: v1
kind: Service
metadata:
  name: frontend-nodeport
  namespace: guestbook
spec:
  selector:
    app: guestbook
    tier: frontend
  ports:
  - name: http
    port: 80
    nodePort: 31000
  type: NodePort
